/*
 * Generated by http://www.springfuse.com
 */
package com.morgajel.spoe.util;

import static org.junit.Assert.*;
import org.junit.Test;

public class StringUtilTest {

    @Test
    public void testIsTrue() {
        assertFalse(StringUtil.isTrue(null));
        assertFalse(StringUtil.isTrue("0"));
        assertFalse(StringUtil.isTrue("false"));
        assertTrue(StringUtil.isTrue("1"));
        assertTrue(StringUtil.isTrue("true"));
        assertTrue(StringUtil.isTrue("yes"));
        assertTrue(StringUtil.isTrue(" yes "));
    }

    @Test
    public void testIsNumeric() {
        assertFalse(StringUtil.isNumeric(null));
        assertTrue(StringUtil.isNumeric("0"));
        assertTrue(StringUtil.isNumeric("" + (-Long.MAX_VALUE)));
        assertTrue(StringUtil.isNumeric("" + Long.MAX_VALUE));
    }

    @Test
    public void testHasLength() {
        assertFalse(StringUtil.hasLength(null));
        assertFalse(StringUtil.hasLength(""));
        assertTrue(StringUtil.hasLength("a"));
    }

    @Test
    public void testFindStringInArray() {
        assertEquals(-1, StringUtil.findStringInArray("world", new String[] {}));
        assertEquals(2, StringUtil.findStringInArray("world", new String[] {"toto", "hello", "world" }));
    }

    @Test
    public void testGetRandomCode() {
        assertFalse(StringUtil.getRandomCode().equals(StringUtil.getRandomCode()));
    }

    @Test
    public void testTruncate() {
        assertEquals("he", StringUtil.truncate("hello", 2));
        assertEquals("hello", StringUtil.truncate("hello", 5));
        assertEquals("hello", StringUtil.truncate("hello", 6));
    }

    @Test
    public void testChunk() {
        assertEquals("...", StringUtil.chunk("hello", 0));
        assertEquals("...", StringUtil.chunk("hello", 1));
        assertEquals("...", StringUtil.chunk("hello", 3));
        assertEquals("h...", StringUtil.chunk("hello", 4));
        assertEquals("hello", StringUtil.chunk("hello", 5));
        assertEquals("hello", StringUtil.chunk("hello", 6));
    }
}
