/*
 * Generated by http://www.springfuse.com
 */
package com.morgajel.spoe.manager;

//import java.util.Date;

import com.morgajel.spoe.domain.AccountModel;
import com.morgajel.spoe.manager.support.GenericEntityService;


/**
 * The AccountManager is a data-centric service for the AccountModel entity.
 * It provides the expected methods to get/delete a AccountModel instance
 * plus some methods to perform searches.
 * 
 * Search logic is driven by 2 kinds of parameters: a AccountModel instance used
 * as a properties holder against which the search will be performed and a SearchTemplate
 * instance from where you can control your search options including the usage
 * of named queries.
 */
public interface AccountManager extends GenericEntityService<AccountModel, Integer> {

    /**
     * Return the persistent instance of AccountModel with the given unique property value email, 
     * or null if there is no such persistent instance. 
     *
     * @param email the unique value
     * @return the corresponding AccountModel persistent instance or null
     */
    AccountModel getByEmail(String email);

    /**
     * Delete a AccountModel using the unique column email
     *
     * @param email the unique value
     */
    void deleteByEmail(String email);

    /**
     * Return the persistent instance of AccountModel with the given unique property value username, 
     * or null if there is no such persistent instance. 
     *
     * @param username the unique value
     * @return the corresponding AccountModel persistent instance or null
     */
    AccountModel getByUsername(String username);

    /**
     * Delete a AccountModel using the unique column username
     *
     * @param username the unique value
     */
    void deleteByUsername(String username);
}
